export const currencies = [
  {
    name: 'Afghanistan',
    currencyName: 'Afghan Afghani',
    currencyValue: 0.51,
    currencySymbol: '؋',
    flagIcon: '🇦🇫',
  },
  {
    name: 'Albania',
    currencyName: 'Albanian Lek',
    currencyValue: 0.0098,
    currencySymbol: 'L',
    flagIcon: '🇦🇱',
  },
  {
    name: 'Algeria',
    currencyName: 'Algerian Dinar',
    currencyValue: 0.13,
    currencySymbol: 'د.ج',
    flagIcon: '🇩🇿',
  },
  {
    name: 'Andorra',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇦🇩',
  },
  {
    name: 'Angola',
    currencyName: 'Angolan Kwanza',
    currencyValue: 0.0019,
    currencySymbol: 'Kz',
    flagIcon: '🇦🇴',
  },
  {
    name: 'Antigua and Barbuda',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇦🇬',
  },
  {
    name: 'Argentina',
    currencyName: 'Argentine Peso',
    currencyValue: 0.01,
    currencySymbol: '$',
    flagIcon: '🇦🇷',
  },
  {
    name: 'Armenia',
    currencyName: 'Armenian Dram',
    currencyValue: 0.0021,
    currencySymbol: '֏',
    flagIcon: '🇦🇲',
  },
  {
    name: 'Australia',
    currencyName: 'Australian Dollar',
    currencyValue: 1.31,
    currencySymbol: '$',
    flagIcon: '🇦🇺',
  },
  {
    name: 'Austria',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇦🇹',
  },
  {
    name: 'Azerbaijan',
    currencyName: 'Azerbaijani Manat',
    currencyValue: 0.059,
    currencySymbol: '₼',
    flagIcon: '🇦🇿',
  },
  {
    name: 'Bahamas',
    currencyName: 'Bahamian Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇧🇸',
  },
  {
    name: 'Bahrain',
    currencyName: 'Bahraini Dinar',
    currencyValue: 2.65,
    currencySymbol: 'BD',
    flagIcon: '🇧🇭',
  },
  {
    name: 'Bangladesh',
    currencyName: 'Bangladeshi Taka',
    currencyValue: 0.012,
    currencySymbol: '৳',
    flagIcon: '🇧🇩',
  },
  {
    name: 'Barbados',
    currencyName: 'Barbadian Dollar',
    currencyValue: 0.5,
    currencySymbol: 'Bds$',
    flagIcon: '🇧🇧',
  },
  {
    name: 'Belarus',
    currencyName: 'Belarusian Ruble',
    currencyValue: 0.04,
    currencySymbol: 'Br',
    flagIcon: '🇧🇾',
  },
  {
    name: 'Belgium',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇧🇪',
  },
  {
    name: 'Belize',
    currencyName: 'Belize Dollar',
    currencyValue: 0.5,
    currencySymbol: 'BZ$',
    flagIcon: '🇧🇿',
  },
  {
    name: 'Benin',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇧🇯',
  },
  {
    name: 'Bhutan',
    currencyName: 'Bhutanese Ngultrum',
    currencyValue: 0.014,
    currencySymbol: 'Nu.',
    flagIcon: '🇧🇹',
  },
  {
    name: 'Bolivia',
    currencyName: 'Bolivian Boliviano',
    currencyValue: 0.14,
    currencySymbol: 'Bs.',
    flagIcon: '🇧🇴',
  },
  {
    name: 'Bosnia and Herzegovina',
    currencyName: 'Bosnia and Herzegovina Convertible Mark',
    currencyValue: 0.49,
    currencySymbol: 'KM',
    flagIcon: '🇧🇦',
  },
  {
    name: 'Botswana',
    currencyName: 'Botswana Pula',
    currencyValue: 0.089,
    currencySymbol: 'P',
    flagIcon: '🇧🇼',
  },
  {
    name: 'Brazil',
    currencyName: 'Brazilian Real',
    currencyValue: 0.19,
    currencySymbol: 'R$',
    flagIcon: '🇧🇷',
  },
  {
    name: 'Brunei',
    currencyName: 'Brunei Dollar',
    currencyValue: 0.74,
    currencySymbol: 'B$',
    flagIcon: '🇧🇳',
  },
  {
    name: 'Bulgaria',
    currencyName: 'Bulgarian Lev',
    currencyValue: 0.52,
    currencySymbol: 'лв',
    flagIcon: '🇧🇬',
  },
  {
    name: 'Burkina Faso',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇧🇫',
  },
  {
    name: 'Burundi',
    currencyName: 'Burundian Franc',
    currencyValue: 0.0005,
    currencySymbol: 'FBu',
    flagIcon: '🇧🇮',
  },
  {
    name: 'Cabo Verde',
    currencyName: 'Cape Verdean Escudo',
    currencyValue: 0.011,
    currencySymbol: 'CVE',
    flagIcon: '🇨🇻',
  },
  {
    name: 'Cambodia',
    currencyName: 'Cambodian Riel',
    currencyValue: 0.00025,
    currencySymbol: '៛',
    flagIcon: '🇰🇭',
  },
  {
    name: 'Cameroon',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇲',
  },
  {
    name: 'Canada',
    currencyName: 'Canadian Dollar',
    currencyValue: 1.25,
    currencySymbol: '$',
    flagIcon: '🇨🇦',
  },
  {
    name: 'Central African Republic',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇫',
  },
  {
    name: 'Chad',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇹🇩',
  },
  {
    name: 'Chile',
    currencyName: 'Chilean Peso',
    currencyValue: 0.0012,
    currencySymbol: '$',
    flagIcon: '🇨🇱',
  },
  {
    name: 'China',
    currencyName: 'Chinese Yuan',
    currencyValue: 0.16,
    currencySymbol: '¥',
    flagIcon: '🇨🇳',
  },
  {
    name: 'Colombia',
    currencyName: 'Colombian Peso',
    currencyValue: 0.00026,
    currencySymbol: '$',
    flagIcon: '🇨🇴',
  },
  {
    name: 'Comoros',
    currencyName: 'Comorian Franc',
    currencyValue: 0.0022,
    currencySymbol: 'CF',
    flagIcon: '🇰🇲',
  },
  {
    name: 'Congo (Brazzaville)',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇬',
  },
  {
    name: 'Congo (Kinshasa)',
    currencyName: 'Congolese Franc',
    currencyValue: 0.00048,
    currencySymbol: 'FC',
    flagIcon: '🇨🇩',
  },
  {
    name: 'Costa Rica',
    currencyName: 'Costa Rican Colón',
    currencyValue: 0.0016,
    currencySymbol: '₡',
    flagIcon: '🇨🇷',
  },
  {
    name: 'Croatia',
    currencyName: 'Croatian Kuna',
    currencyValue: 0.16,
    currencySymbol: 'kn',
    flagIcon: '🇭🇷',
  },
  {
    name: 'Cuba',
    currencyName: 'Cuban Peso',
    currencyValue: 0.04,
    currencySymbol: '$',
    flagIcon: '🇨🇺',
  },
  {
    name: 'Cyprus',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇨🇾',
  },
  {
    name: 'Czech Republic',
    currencyName: 'Czech Koruna',
    currencyValue: 0.045,
    currencySymbol: 'Kč',
    flagIcon: '🇨🇿',
  },
  {
    name: 'Denmark',
    currencyName: 'Danish Krone',
    currencyValue: 0.16,
    currencySymbol: 'kr',
    flagIcon: '🇩🇰',
  },
  {
    name: 'Djibouti',
    currencyName: 'Djiboutian Franc',
    currencyValue: 0.0057,
    currencySymbol: 'Fdj',
    flagIcon: '🇩🇯',
  },
  {
    name: 'Dominica',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇩🇲',
  },
  {
    name: 'Dominican Republic',
    currencyName: 'Dominican Peso',
    currencyValue: 0.018,
    currencySymbol: 'RD$',
    flagIcon: '🇩🇴',
  },
  {
    name: 'Ecuador',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇪🇨',
  },
  {
    name: 'Egypt',
    currencyName: 'Egyptian Pound',
    currencyValue: 0.063,
    currencySymbol: 'E£',
    flagIcon: '🇪🇬',
  },
  {
    name: 'El Salvador',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇸🇻',
  },
  {
    name: 'Equatorial Guinea',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇬🇶',
  },
  {
    name: 'Eritrea',
    currencyName: 'Eritrean Nakfa',
    currencyValue: 0.067,
    currencySymbol: 'Nfk',
    flagIcon: '🇪🇷',
  },
  {
    name: 'Estonia',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇪🇪',
  },
  {
    name: 'Eswatini',
    currencyName: 'Swazi Lilangeni',
    currencyValue: 0.059,
    currencySymbol: 'E',
    flagIcon: '🇸🇿',
  },
  {
    name: 'Ethiopia',
    currencyName: 'Ethiopian Birr',
    currencyValue: 0.022,
    currencySymbol: 'Br',
    flagIcon: '🇪🇹',
  },
  {
    name: 'Afghanistan',
    currencyName: 'Afghan Afghani',
    currencyValue: 0.51,
    currencySymbol: '؋',
    flagIcon: '🇦🇫',
  },
  {
    name: 'Albania',
    currencyName: 'Albanian Lek',
    currencyValue: 0.0098,
    currencySymbol: 'L',
    flagIcon: '🇦🇱',
  },
  {
    name: 'Algeria',
    currencyName: 'Algerian Dinar',
    currencyValue: 0.13,
    currencySymbol: 'د.ج',
    flagIcon: '🇩🇿',
  },
  {
    name: 'Andorra',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇦🇩',
  },
  {
    name: 'Angola',
    currencyName: 'Angolan Kwanza',
    currencyValue: 0.0019,
    currencySymbol: 'Kz',
    flagIcon: '🇦🇴',
  },
  {
    name: 'Antigua and Barbuda',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇦🇬',
  },
  {
    name: 'Argentina',
    currencyName: 'Argentine Peso',
    currencyValue: 0.01,
    currencySymbol: '$',
    flagIcon: '🇦🇷',
  },
  {
    name: 'Armenia',
    currencyName: 'Armenian Dram',
    currencyValue: 0.0021,
    currencySymbol: '֏',
    flagIcon: '🇦🇲',
  },
  {
    name: 'Australia',
    currencyName: 'Australian Dollar',
    currencyValue: 1.31,
    currencySymbol: '$',
    flagIcon: '🇦🇺',
  },
  {
    name: 'Austria',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇦🇹',
  },
  {
    name: 'Azerbaijan',
    currencyName: 'Azerbaijani Manat',
    currencyValue: 0.059,
    currencySymbol: '₼',
    flagIcon: '🇦🇿',
  },
  {
    name: 'Bahamas',
    currencyName: 'Bahamian Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇧🇸',
  },
  {
    name: 'Bahrain',
    currencyName: 'Bahraini Dinar',
    currencyValue: 2.65,
    currencySymbol: 'BD',
    flagIcon: '🇧🇭',
  },
  {
    name: 'Bangladesh',
    currencyName: 'Bangladeshi Taka',
    currencyValue: 0.012,
    currencySymbol: '৳',
    flagIcon: '🇧🇩',
  },
  {
    name: 'Barbados',
    currencyName: 'Barbadian Dollar',
    currencyValue: 0.5,
    currencySymbol: 'Bds$',
    flagIcon: '🇧🇧',
  },
  {
    name: 'Belarus',
    currencyName: 'Belarusian Ruble',
    currencyValue: 0.04,
    currencySymbol: 'Br',
    flagIcon: '🇧🇾',
  },
  {
    name: 'Belgium',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇧🇪',
  },
  {
    name: 'Belize',
    currencyName: 'Belize Dollar',
    currencyValue: 0.5,
    currencySymbol: 'BZ$',
    flagIcon: '🇧🇿',
  },
  {
    name: 'Benin',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇧🇯',
  },
  {
    name: 'Bhutan',
    currencyName: 'Bhutanese Ngultrum',
    currencyValue: 0.014,
    currencySymbol: 'Nu.',
    flagIcon: '🇧🇹',
  },
  {
    name: 'Bolivia',
    currencyName: 'Bolivian Boliviano',
    currencyValue: 0.14,
    currencySymbol: 'Bs.',
    flagIcon: '🇧🇴',
  },
  {
    name: 'Bosnia and Herzegovina',
    currencyName: 'Bosnia and Herzegovina Convertible Mark',
    currencyValue: 0.49,
    currencySymbol: 'KM',
    flagIcon: '🇧🇦',
  },
  {
    name: 'Botswana',
    currencyName: 'Botswana Pula',
    currencyValue: 0.089,
    currencySymbol: 'P',
    flagIcon: '🇧🇼',
  },
  {
    name: 'Brazil',
    currencyName: 'Brazilian Real',
    currencyValue: 0.19,
    currencySymbol: 'R$',
    flagIcon: '🇧🇷',
  },
  {
    name: 'Brunei',
    currencyName: 'Brunei Dollar',
    currencyValue: 0.74,
    currencySymbol: 'B$',
    flagIcon: '🇧🇳',
  },
  {
    name: 'Bulgaria',
    currencyName: 'Bulgarian Lev',
    currencyValue: 0.52,
    currencySymbol: 'лв',
    flagIcon: '🇧🇬',
  },
  {
    name: 'Burkina Faso',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇧🇫',
  },
  {
    name: 'Burundi',
    currencyName: 'Burundian Franc',
    currencyValue: 0.0005,
    currencySymbol: 'FBu',
    flagIcon: '🇧🇮',
  },
  {
    name: 'Cabo Verde',
    currencyName: 'Cape Verdean Escudo',
    currencyValue: 0.011,
    currencySymbol: 'CVE',
    flagIcon: '🇨🇻',
  },
  {
    name: 'Cambodia',
    currencyName: 'Cambodian Riel',
    currencyValue: 0.00025,
    currencySymbol: '៛',
    flagIcon: '🇰🇭',
  },
  {
    name: 'Cameroon',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇲',
  },
  {
    name: 'Canada',
    currencyName: 'Canadian Dollar',
    currencyValue: 1.25,
    currencySymbol: '$',
    flagIcon: '🇨🇦',
  },
  {
    name: 'Central African Republic',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇫',
  },
  {
    name: 'Chad',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇹🇩',
  },
  {
    name: 'Chile',
    currencyName: 'Chilean Peso',
    currencyValue: 0.0012,
    currencySymbol: '$',
    flagIcon: '🇨🇱',
  },
  {
    name: 'China',
    currencyName: 'Chinese Yuan',
    currencyValue: 0.16,
    currencySymbol: '¥',
    flagIcon: '🇨🇳',
  },
  {
    name: 'Colombia',
    currencyName: 'Colombian Peso',
    currencyValue: 0.00026,
    currencySymbol: '$',
    flagIcon: '🇨🇴',
  },
  {
    name: 'Comoros',
    currencyName: 'Comorian Franc',
    currencyValue: 0.0022,
    currencySymbol: 'CF',
    flagIcon: '🇰🇲',
  },
  {
    name: 'Congo (Brazzaville)',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇨🇬',
  },
  {
    name: 'Congo (Kinshasa)',
    currencyName: 'Congolese Franc',
    currencyValue: 0.00048,
    currencySymbol: 'FC',
    flagIcon: '🇨🇩',
  },
  {
    name: 'Costa Rica',
    currencyName: 'Costa Rican Colón',
    currencyValue: 0.0016,
    currencySymbol: '₡',
    flagIcon: '🇨🇷',
  },
  {
    name: 'Croatia',
    currencyName: 'Croatian Kuna',
    currencyValue: 0.16,
    currencySymbol: 'kn',
    flagIcon: '🇭🇷',
  },
  {
    name: 'Cuba',
    currencyName: 'Cuban Peso',
    currencyValue: 0.04,
    currencySymbol: '$',
    flagIcon: '🇨🇺',
  },
  {
    name: 'Cyprus',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇨🇾',
  },
  {
    name: 'Czech Republic',
    currencyName: 'Czech Koruna',
    currencyValue: 0.045,
    currencySymbol: 'Kč',
    flagIcon: '🇨🇿',
  },
  {
    name: 'Denmark',
    currencyName: 'Danish Krone',
    currencyValue: 0.16,
    currencySymbol: 'kr',
    flagIcon: '🇩🇰',
  },
  {
    name: 'Djibouti',
    currencyName: 'Djiboutian Franc',
    currencyValue: 0.0057,
    currencySymbol: 'Fdj',
    flagIcon: '🇩🇯',
  },
  {
    name: 'Dominica',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇩🇲',
  },
  {
    name: 'Dominican Republic',
    currencyName: 'Dominican Peso',
    currencyValue: 0.018,
    currencySymbol: 'RD$',
    flagIcon: '🇩🇴',
  },
  {
    name: 'Ecuador',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇪🇨',
  },
  {
    name: 'Egypt',
    currencyName: 'Egyptian Pound',
    currencyValue: 0.063,
    currencySymbol: 'E£',
    flagIcon: '🇪🇬',
  },
  {
    name: 'El Salvador',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇸🇻',
  },
  {
    name: 'Equatorial Guinea',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇬🇶',
  },
  {
    name: 'Eritrea',
    currencyName: 'Eritrean Nakfa',
    currencyValue: 0.067,
    currencySymbol: 'Nfk',
    flagIcon: '🇪🇷',
  },
  {
    name: 'Estonia',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇪🇪',
  },
  {
    name: 'Eswatini',
    currencyName: 'Swazi Lilangeni',
    currencyValue: 0.059,
    currencySymbol: 'E',
    flagIcon: '🇸🇿',
  },
  {
    name: 'Ethiopia',
    currencyName: 'Ethiopian Birr',
    currencyValue: 0.022,
    currencySymbol: 'Br',
    flagIcon: '🇪🇹',
  },
  {
    name: 'Fiji',
    currencyName: 'Fijian Dollar',
    currencyValue: 0.49,
    currencySymbol: 'FJ$',
    flagIcon: '🇫🇯',
  },
  {
    name: 'Finland',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇫🇮',
  },
  {
    name: 'France',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇫🇷',
  },
  {
    name: 'Gabon',
    currencyName: 'Central African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇬🇦',
  },
  {
    name: 'Gambia',
    currencyName: 'Gambian Dalasi',
    currencyValue: 0.019,
    currencySymbol: 'D',
    flagIcon: '🇬🇲',
  },
  {
    name: 'Georgia',
    currencyName: 'Georgian Lari',
    currencyValue: 0.28,
    currencySymbol: '₾',
    flagIcon: '🇬🇪',
  },
  {
    name: 'Germany',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇩🇪',
  },
  {
    name: 'Ghana',
    currencyName: 'Ghanaian Cedi',
    currencyValue: 0.17,
    currencySymbol: '₵',
    flagIcon: '🇬🇭',
  },
  {
    name: 'Greece',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇬🇷',
  },
  {
    name: 'Grenada',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇬🇩',
  },
  {
    name: 'Guatemala',
    currencyName: 'Guatemalan Quetzal',
    currencyValue: 0.13,
    currencySymbol: 'Q',
    flagIcon: '🇬🇹',
  },
  {
    name: 'Guinea',
    currencyName: 'Guinean Franc',
    currencyValue: 0.00011,
    currencySymbol: 'FG',
    flagIcon: '🇬🇳',
  },
  {
    name: 'Guinea-Bissau',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇬🇼',
  },
  {
    name: 'Guyana',
    currencyName: 'Guyanese Dollar',
    currencyValue: 0.0047,
    currencySymbol: 'GY$',
    flagIcon: '🇬🇾',
  },
  {
    name: 'Haiti',
    currencyName: 'Haitian Gourde',
    currencyValue: 0.0094,
    currencySymbol: 'G',
    flagIcon: '🇭🇹',
  },
  {
    name: 'Honduras',
    currencyName: 'Honduran Lempira',
    currencyValue: 0.04,
    currencySymbol: 'L',
    flagIcon: '🇭🇳',
  },
  {
    name: 'Hungary',
    currencyName: 'Hungarian Forint',
    currencyValue: 0.0028,
    currencySymbol: 'Ft',
    flagIcon: '🇭🇺',
  },
  {
    name: 'Iceland',
    currencyName: 'Icelandic Króna',
    currencyValue: 0.0079,
    currencySymbol: 'kr',
    flagIcon: '🇮🇸',
  },
  {
    name: 'India',
    currencyName: 'Indian Rupee',
    currencyValue: 0.013,
    currencySymbol: '₹',
    flagIcon: '🇮🇳',
  },
  {
    name: 'Indonesia',
    currencyName: 'Indonesian Rupiah',
    currencyValue: 0.000069,
    currencySymbol: 'Rp',
    flagIcon: '🇮🇩',
  },
  {
    name: 'Iran',
    currencyName: 'Iranian Rial',
    currencyValue: 0.000024,
    currencySymbol: '﷼',
    flagIcon: '🇮🇷',
  },
  {
    name: 'Iraq',
    currencyName: 'Iraqi Dinar',
    currencyValue: 0.00068,
    currencySymbol: 'ع.د',
    flagIcon: '🇮🇶',
  },
  {
    name: 'Ireland',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇮🇪',
  },
  {
    name: 'Israel',
    currencyName: 'Israeli New Shekel',
    currencyValue: 0.31,
    currencySymbol: '₪',
    flagIcon: '🇮🇱',
  },
  {
    name: 'Italy',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇮🇹',
  },
  {
    name: 'Jamaica',
    currencyName: 'Jamaican Dollar',
    currencyValue: 0.0067,
    currencySymbol: 'J$',
    flagIcon: '🇯🇲',
  },
  {
    name: 'Japan',
    currencyName: 'Japanese Yen',
    currencyValue: 0.0091,
    currencySymbol: '¥',
    flagIcon: '🇯🇵',
  },
  {
    name: 'Jordan',
    currencyName: 'Jordanian Dinar',
    currencyValue: 1.41,
    currencySymbol: 'JD',
    flagIcon: '🇯🇴',
  },
  {
    name: 'Kazakhstan',
    currencyName: 'Kazakhstani Tenge',
    currencyValue: 0.0023,
    currencySymbol: '₸',
    flagIcon: '🇰🇿',
  },
  {
    name: 'Kenya',
    currencyName: 'Kenyan Shilling',
    currencyValue: 0.0087,
    currencySymbol: 'KSh',
    flagIcon: '🇰🇪',
  },
  {
    name: 'Kiribati',
    currencyName: 'Kiribati Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇰🇮',
  },
  {
    name: 'Korea, North',
    currencyName: 'North Korean Won',
    currencyValue: 0.00093,
    currencySymbol: '₩',
    flagIcon: '🇰🇵',
  },
  {
    name: 'Korea, South',
    currencyName: 'South Korean Won',
    currencyValue: 0.00084,
    currencySymbol: '₩',
    flagIcon: '🇰🇷',
  },
  {
    name: 'Kosovo',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇽🇰',
  },
  {
    name: 'Kuwait',
    currencyName: 'Kuwaiti Dinar',
    currencyValue: 3.32,
    currencySymbol: 'KD',
    flagIcon: '🇰🇼',
  },
  {
    name: 'Kyrgyzstan',
    currencyName: 'Kyrgyzstani Som',
    currencyValue: 0.011,
    currencySymbol: 'с',
    flagIcon: '🇰🇬',
  },
  {
    name: 'Laos',
    currencyName: 'Lao Kip',
    currencyValue: 0.0001,
    currencySymbol: '₭',
    flagIcon: '🇱🇦',
  },
  {
    name: 'Latvia',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇱🇻',
  },
  {
    name: 'Lebanon',
    currencyName: 'Lebanese Pound',
    currencyValue: 0.00066,
    currencySymbol: 'ل.ل',
    flagIcon: '🇱🇧',
  },
  {
    name: 'Lesotho',
    currencyName: 'Lesotho Loti',
    currencyValue: 0.059,
    currencySymbol: 'L',
    flagIcon: '🇱🇸',
  },
  {
    name: 'Liberia',
    currencyName: 'Liberian Dollar',
    currencyValue: 0.0061,
    currencySymbol: 'L$',
    flagIcon: '🇱🇷',
  },
  {
    name: 'Libya',
    currencyName: 'Libyan Dinar',
    currencyValue: 0.22,
    currencySymbol: 'ل.د',
    flagIcon: '🇱🇾',
  },
  {
    name: 'Liechtenstein',
    currencyName: 'Swiss Franc',
    currencyValue: 1.11,
    currencySymbol: 'CHF',
    flagIcon: '🇱🇮',
  },
  {
    name: 'Lithuania',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇱🇹',
  },
  {
    name: 'Luxembourg',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇱🇺',
  },
  {
    name: 'Madagascar',
    currencyName: 'Malagasy Ariary',
    currencyValue: 0.00023,
    currencySymbol: 'Ar',
    flagIcon: '🇲🇬',
  },
  {
    name: 'Malawi',
    currencyName: 'Malawian Kwacha',
    currencyValue: 0.0012,
    currencySymbol: 'MK',
    flagIcon: '🇲🇼',
  },
  {
    name: 'Malaysia',
    currencyName: 'Malaysian Ringgit',
    currencyValue: 0.24,
    currencySymbol: 'RM',
    flagIcon: '🇲🇾',
  },
  {
    name: 'Maldives',
    currencyName: 'Maldivian Rufiyaa',
    currencyValue: 0.065,
    currencySymbol: 'Rf',
    flagIcon: '🇲🇻',
  },
  {
    name: 'Mali',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇲🇱',
  },
  {
    name: 'Malta',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇲🇹',
  },
  {
    name: 'Marshall Islands',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇲🇭',
  },
  {
    name: 'Mauritania',
    currencyName: 'Mauritanian Ouguiya',
    currencyValue: 0.0022,
    currencySymbol: 'UM',
    flagIcon: '🇲🇷',
  },
  {
    name: 'Mauritius',
    currencyName: 'Mauritian Rupee',
    currencyValue: 0.022,
    currencySymbol: '₨',
    flagIcon: '🇲🇺',
  },
  {
    name: 'Mexico',
    currencyName: 'Mexican Peso',
    currencyValue: 0.05,
    currencySymbol: '$',
    flagIcon: '🇲🇽',
  },
  {
    name: 'Micronesia',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇫🇲',
  },
  {
    name: 'Moldova',
    currencyName: 'Moldovan Leu',
    currencyValue: 0.054,
    currencySymbol: 'L',
    flagIcon: '🇲🇩',
  },
  {
    name: 'Monaco',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇲🇨',
  },
  {
    name: 'Mongolia',
    currencyName: 'Mongolian Tögrög',
    currencyValue: 0.00035,
    currencySymbol: '₮',
    flagIcon: '🇲🇳',
  },
  {
    name: 'Montenegro',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇲🇪',
  },
  {
    name: 'Morocco',
    currencyName: 'Moroccan Dirham',
    currencyValue: 0.11,
    currencySymbol: 'د.م.',
    flagIcon: '🇲🇦',
  },
  {
    name: 'Mozambique',
    currencyName: 'Mozambican Metical',
    currencyValue: 0.015,
    currencySymbol: 'MT',
    flagIcon: '🇲🇿',
  },
  {
    name: 'Myanmar',
    currencyName: 'Burmese Kyat',
    currencyValue: 0.00012,
    currencySymbol: 'Ks',
    flagIcon: '🇲🇲',
  },
  {
    name: 'Namibia',
    currencyName: 'Namibian Dollar',
    currencyValue: 0.069,
    currencySymbol: 'N$',
    flagIcon: '🇳🇦',
  },
  {
    name: 'Nauru',
    currencyName: 'Australian Dollar',
    currencyValue: 1.31,
    currencySymbol: '$',
    flagIcon: '🇳🇷',
  },
  {
    name: 'Nepal',
    currencyName: 'Nepalese Rupee',
    currencyValue: 0.0084,
    currencySymbol: '₨',
    flagIcon: '🇳🇵',
  },
  {
    name: 'Netherlands',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇳🇱',
  },
  {
    name: 'New Zealand',
    currencyName: 'New Zealand Dollar',
    currencyValue: 1.41,
    currencySymbol: '$',
    flagIcon: '🇳🇿',
  },
  {
    name: 'Nicaragua',
    currencyName: 'Nicaraguan Córdoba',
    currencyValue: 0.028,
    currencySymbol: 'C$',
    flagIcon: '🇳🇮',
  },
  {
    name: 'Niger',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇳🇪',
  },
  {
    name: 'Nigeria',
    currencyName: 'Nigerian Naira',
    currencyValue: 0.0024,
    currencySymbol: '₦',
    flagIcon: '🇳🇬',
  },
  {
    name: 'North Macedonia',
    currencyName: 'Macedonian Denar',
    currencyValue: 0.02,
    currencySymbol: 'ден',
    flagIcon: '🇲🇰',
  },
  {
    name: 'Norway',
    currencyName: 'Norwegian Krone',
    currencyValue: 0.12,
    currencySymbol: 'kr',
    flagIcon: '🇳🇴',
  },
  {
    name: 'Oman',
    currencyName: 'Omani Rial',
    currencyValue: 2.6,
    currencySymbol: 'ر.ع.',
    flagIcon: '🇴🇲',
  },
  {
    name: 'Pakistan',
    currencyName: 'Pakistani Rupee',
    currencyValue: 0.0059,
    currencySymbol: '₨',
    flagIcon: '🇵🇰',
  },
  {
    name: 'Palau',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇵🇼',
  },
  {
    name: 'Palestine',
    currencyName: 'Israeli New Shekel',
    currencyValue: 0.31,
    currencySymbol: '₪',
    flagIcon: '🇵🇸',
  },
  {
    name: 'Panama',
    currencyName: 'Panamanian Balboa',
    currencyValue: 1.0,
    currencySymbol: 'B/.',
    flagIcon: '🇵🇦',
  },
  {
    name: 'Papua New Guinea',
    currencyName: 'Papua New Guinean Kina',
    currencyValue: 0.28,
    currencySymbol: 'K',
    flagIcon: '🇵🇬',
  },
  {
    name: 'Paraguay',
    currencyName: 'Paraguayan Guarani',
    currencyValue: 0.00014,
    currencySymbol: '₲',
    flagIcon: '🇵🇾',
  },
  {
    name: 'Peru',
    currencyName: 'Peruvian Nuevo Sol',
    currencyValue: 0.24,
    currencySymbol: 'S/.',
    flagIcon: '🇵🇪',
  },
  {
    name: 'Philippines',
    currencyName: 'Philippine Peso',
    currencyValue: 0.02,
    currencySymbol: '₱',
    flagIcon: '🇵🇭',
  },
  {
    name: 'Poland',
    currencyName: 'Polish Złoty',
    currencyValue: 0.23,
    currencySymbol: 'zł',
    flagIcon: '🇵🇱',
  },
  {
    name: 'Portugal',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇵🇹',
  },
  {
    name: 'Qatar',
    currencyName: 'Qatari Riyal',
    currencyValue: 0.27,
    currencySymbol: 'ر.ق',
    flagIcon: '🇶🇦',
  },
  {
    name: 'Romania',
    currencyName: 'Romanian Leu',
    currencyValue: 0.21,
    currencySymbol: 'lei',
    flagIcon: '🇷🇴',
  },
  {
    name: 'Russia',
    currencyName: 'Russian Ruble',
    currencyValue: 0.013,
    currencySymbol: '₽',
    flagIcon: '🇷🇺',
  },
  {
    name: 'Rwanda',
    currencyName: 'Rwandan Franc',
    currencyValue: 0.001,
    currencySymbol: 'FRw',
    flagIcon: '🇷🇼',
  },
  {
    name: 'Saint Kitts and Nevis',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇰🇳',
  },
  {
    name: 'Saint Lucia',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇱🇨',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    currencyName: 'East Caribbean Dollar',
    currencyValue: 0.37,
    currencySymbol: 'EC$',
    flagIcon: '🇻🇨',
  },
  {
    name: 'Samoa',
    currencyName: 'Samoan Tālā',
    currencyValue: 0.4,
    currencySymbol: 'T',
    flagIcon: '🇼🇸',
  },
  {
    name: 'San Marino',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇸🇲',
  },
  {
    name: 'Sao Tome and Principe',
    currencyName: 'São Tomé and Príncipe Dobra',
    currencyValue: 0.000045,
    currencySymbol: 'Db',
    flagIcon: '🇸🇹',
  },
  {
    name: 'Saudi Arabia',
    currencyName: 'Saudi Riyal',
    currencyValue: 0.27,
    currencySymbol: 'ر.س',
    flagIcon: '🇸🇦',
  },
  {
    name: 'Senegal',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇸🇳',
  },
  {
    name: 'Serbia',
    currencyName: 'Serbian Dinar',
    currencyValue: 0.0094,
    currencySymbol: 'дин.',
    flagIcon: '🇷🇸',
  },
  {
    name: 'Seychelles',
    currencyName: 'Seychellois Rupee',
    currencyValue: 0.059,
    currencySymbol: '₨',
    flagIcon: '🇸🇨',
  },
  {
    name: 'Sierra Leone',
    currencyName: 'Sierra Leonean Leone',
    currencyValue: 0.0001,
    currencySymbol: 'Le',
    flagIcon: '🇸🇱',
  },
  {
    name: 'Singapore',
    currencyName: 'Singapore Dollar',
    currencyValue: 0.73,
    currencySymbol: '$',
    flagIcon: '🇸🇬',
  },
  {
    name: 'Slovakia',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇸🇰',
  },
  {
    name: 'Slovenia',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇸🇮',
  },
  {
    name: 'Solomon Islands',
    currencyName: 'Solomon Islands Dollar',
    currencyValue: 0.13,
    currencySymbol: 'SI$',
    flagIcon: '🇸🇧',
  },
  {
    name: 'Somalia',
    currencyName: 'Somali Shilling',
    currencyValue: 0.0017,
    currencySymbol: 'Sh',
    flagIcon: '🇸🇴',
  },
  {
    name: 'South Africa',
    currencyName: 'South African Rand',
    currencyValue: 0.069,
    currencySymbol: 'R',
    flagIcon: '🇿🇦',
  },
  {
    name: 'South Sudan',
    currencyName: 'South Sudanese Pound',
    currencyValue: 0.0022,
    currencySymbol: '£',
    flagIcon: '🇸🇸',
  },
  {
    name: 'Spain',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇪🇸',
  },
  {
    name: 'Sri Lanka',
    currencyName: 'Sri Lankan Rupee',
    currencyValue: 0.0044,
    currencySymbol: 'රු',
    flagIcon: '🇱🇰',
  },
  {
    name: 'Sudan',
    currencyName: 'Sudanese Pound',
    currencyValue: 0.003,
    currencySymbol: '£',
    flagIcon: '🇸🇩',
  },
  {
    name: 'Suriname',
    currencyName: 'Surinamese Dollar',
    currencyValue: 0.014,
    currencySymbol: '$',
    flagIcon: '🇸🇷',
  },
  {
    name: 'Sweden',
    currencyName: 'Swedish Krona',
    currencyValue: 0.11,
    currencySymbol: 'kr',
    flagIcon: '🇸🇪',
  },
  {
    name: 'Switzerland',
    currencyName: 'Swiss Franc',
    currencyValue: 1.11,
    currencySymbol: 'CHF',
    flagIcon: '🇨🇭',
  },
  {
    name: 'Syria',
    currencyName: 'Syrian Pound',
    currencyValue: 0.00045,
    currencySymbol: '£S',
    flagIcon: '🇸🇾',
  },
  {
    name: 'Taiwan',
    currencyName: 'New Taiwan Dollar',
    currencyValue: 0.036,
    currencySymbol: 'NT$',
    flagIcon: '🇹🇼',
  },
  {
    name: 'Tajikistan',
    currencyName: 'Tajikistani Somoni',
    currencyValue: 0.089,
    currencySymbol: 'SM',
    flagIcon: '🇹🇯',
  },
  {
    name: 'Tanzania',
    currencyName: 'Tanzanian Shilling',
    currencyValue: 0.00043,
    currencySymbol: 'TSh',
    flagIcon: '🇹🇿',
  },
  {
    name: 'Thailand',
    currencyName: 'Thai Baht',
    currencyValue: 0.03,
    currencySymbol: '฿',
    flagIcon: '🇹🇭',
  },
  {
    name: 'Timor-Leste',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇹🇱',
  },
  {
    name: 'Togo',
    currencyName: 'West African CFA Franc',
    currencyValue: 0.0018,
    currencySymbol: 'CFA',
    flagIcon: '🇹🇬',
  },
  {
    name: 'Tonga',
    currencyName: 'Tongan Paʻanga',
    currencyValue: 0.45,
    currencySymbol: 'T$',
    flagIcon: '🇹🇴',
  },
  {
    name: 'Trinidad and Tobago',
    currencyName: 'Trinidad and Tobago Dollar',
    currencyValue: 0.15,
    currencySymbol: 'TT$',
    flagIcon: '🇹🇹',
  },
  {
    name: 'Tunisia',
    currencyName: 'Tunisian Dinar',
    currencyValue: 0.36,
    currencySymbol: 'د.ت',
    flagIcon: '🇹🇳',
  },
  {
    name: 'Turkey',
    currencyName: 'Turkish Lira',
    currencyValue: 0.073,
    currencySymbol: '₺',
    flagIcon: '🇹🇷',
  },
  {
    name: 'Turkmenistan',
    currencyName: 'Turkmenistani Manat',
    currencyValue: 0.028,
    currencySymbol: 'T',
    flagIcon: '🇹🇲',
  },
  {
    name: 'Tuvalu',
    currencyName: 'Tuvaluan Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇹🇻',
  },
  {
    name: 'Uganda',
    currencyName: 'Ugandan Shilling',
    currencyValue: 0.00028,
    currencySymbol: 'USh',
    flagIcon: '🇺🇬',
  },
  {
    name: 'Ukraine',
    currencyName: 'Ukrainian Hryvnia',
    currencyValue: 0.037,
    currencySymbol: '₴',
    flagIcon: '🇺🇦',
  },
  {
    name: 'United Arab Emirates',
    currencyName: 'United Arab Emirates Dirham',
    currencyValue: 0.27,
    currencySymbol: 'د.إ',
    flagIcon: '🇦🇪',
  },
  {
    name: 'United Kingdom',
    currencyName: 'Pound Sterling',
    currencyValue: 1.38,
    currencySymbol: '£',
    flagIcon: '🇬🇧',
  },
  {
    name: 'United States of America',
    currencyName: 'United States Dollar',
    currencyValue: 1.0,
    currencySymbol: '$',
    flagIcon: '🇺🇸',
  },
  {
    name: 'Uruguay',
    currencyName: 'Uruguayan Peso',
    currencyValue: 0.022,
    currencySymbol: '$U',
    flagIcon: '🇺🇾',
  },
  {
    name: 'Uzbekistan',
    currencyName: 'Uzbekistani Som',
    currencyValue: 0.000088,
    currencySymbol: 'soʻm',
    flagIcon: '🇺🇿',
  },
  {
    name: 'Vanuatu',
    currencyName: 'Vanuatu Vatu',
    currencyValue: 0.0089,
    currencySymbol: 'VT',
    flagIcon: '🇻🇺',
  },
  {
    name: 'Vatican City',
    currencyName: 'Euro',
    currencyValue: 0.85,
    currencySymbol: '€',
    flagIcon: '🇻🇦',
  },
  {
    name: 'Venezuela',
    currencyName: 'Venezuelan Bolívar',
    currencyValue: 0.000015,
    currencySymbol: 'Bs.S',
    flagIcon: '🇻🇪',
  },
  {
    name: 'Vietnam',
    currencyName: 'Vietnamese Dong',
    currencyValue: 0.000043,
    currencySymbol: '₫',
    flagIcon: '🇻🇳',
  },
  {
    name: 'Yemen',
    currencyName: 'Yemeni Rial',
    currencyValue: 0.00033,
    currencySymbol: '﷼',
    flagIcon: '🇾🇪',
  },
  {
    name: 'Zambia',
    currencyName: 'Zambian Kwacha',
    currencyValue: 0.045,
    currencySymbol: 'ZK',
    flagIcon: '🇿🇲',
  },
  {
    name: 'Zimbabwe',
    currencyName: 'Zimbabwean Dollar',
    currencyValue: 0.011,
    currencySymbol: 'Z$',
    flagIcon: '🇿🇼',
  },
];
